"""Pure-data containers for strategy signals, trades, and backtest results.

Uses dataclasses (Python 3.7+ stdlib). All fields have defaults so they
can be constructed incrementally during backtest execution.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Optional

import pandas as pd


@dataclass
class Signal:
    """A single trading signal generated by a strategy on one bar."""

    date: pd.Timestamp
    action: str  # "buy", "sell", "hold"
    price: float
    shares: int = 0
    amount: float = 0.0  # shares * price (before commission)
    reason: str = ""  # human-readable rationale

    def __repr__(self) -> str:
        return (
            f"Signal({self.date.date()} {self.action.upper()} "
            f"{self.shares}股 @ {self.price:.3f} {self.reason})"
        )


@dataclass
class Trade:
    """A completed round-trip trade (entry → exit paired)."""

    entry_date: pd.Timestamp
    exit_date: Optional[pd.Timestamp] = None
    entry_price: float = 0.0
    exit_price: Optional[float] = None
    shares: int = 0
    entry_amount: float = 0.0
    exit_amount: Optional[float] = None
    pnl: Optional[float] = None
    pnl_pct: Optional[float] = None
    holding_days: Optional[int] = None

    def __repr__(self) -> str:
        if self.pnl is not None:
            return (
                f"Trade({self.entry_date.date()} → "
                f"{self.exit_date and self.exit_date.date()} "
                f"PNL={self.pnl:+.0f} ({self.pnl_pct:+.1%})"
            )
        return f"Trade({self.entry_date.date()} → OPEN)"


@dataclass
class Position:
    """Current portfolio snapshot at a point in time."""

    cash: float = 0.0
    shares: int = 0
    cost_basis: float = 0.0  # total amount spent on current holdings
    equity: float = 0.0  # cash + shares * current_price

    @property
    def position_value(self) -> float:
        return self.equity - self.cash


@dataclass
class BacktestResult:
    """Complete output from one backtest run."""

    initial_capital: float = 0.0
    final_equity: float = 0.0
    total_return: float = 0.0
    annual_return: float = 0.0
    annual_volatility: float = 0.0
    sharpe_ratio: float = 0.0
    max_drawdown: float = 0.0
    calmar_ratio: float = 0.0
    win_rate: float = 0.0
    total_trades: int = 0
    winning_trades: int = 0
    losing_trades: int = 0
    avg_holding_days: float = 0.0

    # Detailed records
    equity_curve: pd.DataFrame = field(default_factory=pd.DataFrame)
    trades: list[Trade] = field(default_factory=list)
    signals: list[Signal] = field(default_factory=list)

    # Strategy metadata
    strategy_name: str = ""
    strategy_params: dict = field(default_factory=dict)

    def summary(self) -> str:
        """One-line summary for display."""
        return (
            f"{self.strategy_name}: 年化 {self.annual_return:+.1%}  "
            f"Sharpe {self.sharpe_ratio:.2f}  "
            f"MaxDD {self.max_drawdown:.1%}  "
            f"胜率 {self.win_rate:.0%}  "
            f"交易 {self.total_trades}次"
        )
