"""Pure-data containers for strategy signals, trades, and backtest results.

Uses dataclasses (Python 3.7+ stdlib). All fields have defaults so they
can be constructed incrementally during backtest execution.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Optional

import pandas as pd


@dataclass
class Signal:
    """A single trading signal generated by a strategy on one bar."""

    date: pd.Timestamp
    action: str  # "buy", "sell", "hold"
    price: float
    shares: int = 0
    amount: float = 0.0  # shares * price (before commission)
    reason: str = ""  # human-readable rationale

    def __repr__(self) -> str:
        return (
            f"Signal({self.date.date()} {self.action.upper()} "
            f"{self.shares}股 @ {self.price:.3f} {self.reason})"
        )


@dataclass
class Trade:
    """A completed round-trip trade (entry → exit paired)."""

    entry_date: pd.Timestamp
    exit_date: Optional[pd.Timestamp] = None
    entry_price: float = 0.0
    exit_price: Optional[float] = None
    shares: int = 0
    entry_amount: float = 0.0
    exit_amount: Optional[float] = None
    pnl: Optional[float] = None
    pnl_pct: Optional[float] = None
    holding_days: Optional[int] = None

    def __repr__(self) -> str:
        if self.pnl is not None:
            return (
                f"Trade({self.entry_date.date()} → "
                f"{self.exit_date and self.exit_date.date()} "
                f"PNL={self.pnl:+.0f} ({self.pnl_pct:+.1%})"
            )
        return f"Trade({self.entry_date.date()} → OPEN)"


@dataclass
class Position:
    """Current portfolio snapshot at a point in time."""

    cash: float = 0.0
    shares: int = 0
    cost_basis: float = 0.0  # total amount spent on current holdings
    equity: float = 0.0  # cash + shares * current_price

    @property
    def position_value(self) -> float:
        return self.equity - self.cash


@dataclass
class BacktestResult:
    """Complete output from one backtest run."""

    initial_capital: float = 0.0
    final_equity: float = 0.0
    total_return: float = 0.0
    annual_return: float = 0.0
    annual_volatility: float = 0.0
    sharpe_ratio: float = 0.0
    max_drawdown: float = 0.0
    calmar_ratio: float = 0.0
    win_rate: float = 0.0
    total_trades: int = 0
    winning_trades: int = 0
    losing_trades: int = 0
    avg_holding_days: float = 0.0

    # Detailed records
    equity_curve: pd.DataFrame = field(default_factory=pd.DataFrame)
    trades: list[Trade] = field(default_factory=list)
    signals: list[Signal] = field(default_factory=list)

    # Strategy metadata
    strategy_name: str = ""
    strategy_params: dict = field(default_factory=dict)

    def summary(self) -> str:
        """One-line summary for display."""
        return (
            f"{self.strategy_name}: 年化 {self.annual_return:+.1%}  "
            f"Sharpe {self.sharpe_ratio:.2f}  "
            f"MaxDD {self.max_drawdown:.1%}  "
            f"胜率 {self.win_rate:.0%}  "
            f"交易 {self.total_trades}次"
        )


# ---------------------------------------------------------------------------
# Live signal & dashboard cards  (strategy → UI contracts)
# ---------------------------------------------------------------------------


@dataclass
class LiveSignal:
    """Actionable trading recommendation based on current market snapshot.

    Generated by ``BaseStrategy.get_live_signal()`` and rendered by
    ``render_live_signal()`` as a prominent dashboard card.
    """

    action: str = "hold"
    # "buy" | "sell" | "hold" | "wait_for_drop" | "wait_for_rise"

    current_price: Optional[float] = None
    suggested_shares: int = 0
    suggested_amount: float = 0.0

    trigger_description: str = ""
    # e.g. "已跌破4%触发线" / "均线多头排列" / "PE低估区 → 2倍定投"

    next_trigger_price: Optional[float] = None
    reason: str = ""
    urgency_level: str = "low"  # "high" | "medium" | "low"

    portions_used: Optional[int] = None
    portions_total: Optional[int] = None
    current_zone: str = ""  # "低估区" / "第3档" / "多头排列"


@dataclass
class DashboardCard:
    """Strategy-specific information card rendered in the dashboard grid.

    Generated by ``BaseStrategy.get_dashboard_cards()`` and rendered
    by ``render_dashboard_cards()``.
    """

    card_id: str = ""
    title: str = ""
    card_type: str = "metric"
    # "metric" | "trigger" | "progress" | "info" | "warning"

    content: dict = field(default_factory=dict)
    # Arbitrary key-value payload; structure depends on card_type

    priority: int = 2  # 1 = high (first row), 2 = normal, 3 = low
